name: CI

on:
  push:
    branches: 
      - google-code-autoformat-test

jobs:
  formatting:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # v2 minimum required
    - uses: axel-op/googlejavaformat-action@v2.0.0
      with:
        args: "--skip-sorting-imports --skip-removing-unused-imports --replace --set-exit-if-changed --dry-run"
      
